/**
 * Auth.js API route. Re-exports the GET/POST handlers generated by `auth.ts`.
 * Handles sign-in, sign-out, session and CSRF endpoints under /api/auth/*.
 */
import { handlers } from "@/auth";

export const { GET, POST } = handlers;
